# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_glLSqsiKanS-PUol_VpzG02JCVQfwl
"""

pip install pyTelegramBotAPI

import telebot
token = '1011052536:AAHisa_bm9Iaom9JGq8-Qco-xcDOdciaBIo'

bot = telebot.TeleBot(token)

@bot.message_handler(content_types=["text"])
def repeat_all_messages(message): #Название функции не играет никакой роли, в принципе
  bot.send_message(message.chat.id, message.text)


bot.infinity_polling()

import telebot
token = '1011052536:AAHisa_bm9Iaom9JGq8-Qco-xcDOdciaBIo'
import random
devizi = ["Саня верни сотку", "Люблю Ozon" , "Как классно работать в Ozon"]

bot = telebot.TeleBot(token)
@bot.message_handler(content_types=["text"])
def repeat_ozon_message(message):
  if message.text == "Саня":
    message.text = random.choice(devizi)
    bot.send_message(message.chat.id, message.text)
    

      
bot.infinity_polling()

